---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
        exclude: .vscode
      - id: mixed-line-ending
      - id: check-builtin-literals
      - id: check-ast
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-toml
      - id: file-contents-sorter
        files: dictionary.*\.txt$|\.wordlist$
        args: [--ignore-case]
      - id: requirements-txt-fixer
      - id: name-tests-test
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-symlinks

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
      - id: ruff-format
        args: ["--check"]

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--check"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-github-workflows
        args: ["--verbose"]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --no-warnings
          - -d
          - "{extends: relaxed, rules: {line-length: {max: 90}}}"

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.3.0"
    hooks:
      - id: codespell

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "--recursive", "-lll"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs
        args: [--whitespaces-count, "2"]
      - id: chmod
        args: ["644"]
        files: \.md$
      - id: insert-license
        files: \.groovy$
        args:
          - --license-filepath
          - src/license_header.txt
          - --comment-style
          - //
          - --use-current-year
          - --no-extra-eol

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: terraform_tflint

  - repo: https://github.com/Pierre-Sassoulas/black-disable-checker/
    rev: v1.1.3
    hooks:
      - id: black-disable-checker

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: [--disable=MD013]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args:
          [
            "--ignore-missing-imports",
            "--disable-error-code",
            "import-untyped",
            "--disable-error-code",
            "union-attr",
          ]
        require_serial: true

  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.3
    hooks:
      - id: pydocstringformatter
        args: ["--max-summary-lines=2", "--linewrap-full-docstring"]
        files: "pylint"

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.4.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
        exclude: tests(/\w*)*data/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]

  - repo: https://github.com/fpgmaas/deptry.git
    rev: "0.21.1"
    hooks:
      - id: deptry
        args:
          - "app/"

  - repo: local
    hooks:
      - id: disallow-caps
        name: Disallow improper capitalization
        language: pygrep
        entry: PyBind|Numpy|Cmake|CCache|Github|PyTest
        exclude: .pre-commit-config.yaml

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        # Not that problematic to run in parallel see Pre-commit
        # integration in the doc for details
        # require_serial: true
        args: ["-rn", "-sn", "--fail-on=I"]
        exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/
