---
name: Pylint

"on": [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: uv add pylint
        run: |
          uv add pylint

      - name: Analysing the code with pylint
        run: |
          uv run pylint src/*.py
